/*
 * Copyright 2010 Google Inc.  Nethack Public License.
 */

package net.webhack.game.shared;

/**
 * Artifacts (unique objects)
 * 
 * @author Jeff Bailey <jeffbailey@google.com>
 *
 */
public enum Artifact {
	EXCALIBUR,
	STORMBRINGER,
	MJOLLNIR,
	CLEAVER,
	GRIMTOOTH,
	ORCRIST,
	STING,
	MAGICBANE,
	FROST_BRAND,
	FIRE_BRAND,
	DRAGONBANE,
	DEMONBANE,
	WEREBANE,
	GRAYSWANDIR,
	GIANTSLAYER,
	OGRESMASHER,
	TROLLSBANE,
	VORPAL_BLADE,
	SNICKERSNEE,
	SUNSWORD,
	ORB_OF_DETECTION,
	HEART_OF_AHRIMAN,
	SCEPTRE_OF_MIGHT,
	STAFF_OF_AESCULAPIUS,
	MAGIC_MIRROR_OF_MERLIN,
	EYES_OF_THE_OVERWORLD,
	MITRE_OF_HOLINESS,
	LONGBOW_OF_DIANA,
	MASTER_KEY_OF_THIEVERY,
	TSURUGI_OF_MURAMASA,
	YENDORIAN_EXPRESS_CARD,
	ORB_OF_FATE,
	EYE_OF_THE_AETHIOPICA;
}
